import pytest
from .solution import two_sum

def test_nominal_target_match():
    assert two_sum([2, 7, 11, 15], 9) == [0, 1]

# --- STUDENTS MUST COMPLETE THEIR MANUALLY INSIGHTFUL TEST CASES BELOW ---

def test_case_1():
    # test case 1 generated by assistant
    assert two_sum([3, 3], 6) == [0, 1]
