import sys
import subprocess
import re

def get_git_diff():
    try:
        result = subprocess.run(
            ["git", "diff", "HEAD~1", "HEAD", "--", "problems/"],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout
    except Exception as e:
        print(f"Error fetching git diff: {e}")
        sys.exit(1)

def scan_diff():
    diff_text = get_git_diff()
    if not diff_text:
        print("No changes found in problems directory.")
        return

    ai_phrases = [
        r"insert your code here",
        r"generated by assistant",
        r"co-pilot choice",
        r"gpt-",
        r"openai",
        r"\# test case \d+"
    ]
    
    for phrase in ai_phrases:
        if re.search(phrase, diff_text, re.IGNORECASE):
            print("\n❌ [GATE REJECTION] Generic AI boilerplate comment style discovered.")
            print("Action: Remove automated annotations. Detail your assertions manually.")
            sys.exit(1)

    lazy_test_pattern = r"def test_(case_?\d+|test_?\d+)\("
    if re.search(lazy_test_pattern, diff_text, re.IGNORECASE):
        print("\n❌ [GATE REJECTION] Generic non-semantic naming schema flagged.")
        print("Action: Rename tests to describe intent (e.g., test_negative_integers, test_empty_bounds).")
        sys.exit(1)

    print("✅ Static analysis integrity verification passed.")

if __name__ == "__main__":
    scan_diff()
