import re
import subprocess
import sys


def get_git_diff():
    try:
        result = subprocess.run(
            ["git", "diff", "origin/main...HEAD", "--", "problems/"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout
    except Exception:
        try:
            result = subprocess.run(
                ["git", "diff", "HEAD~1", "HEAD", "--", "problems/"],
                capture_output=True,
                text=True,
                check=True,
            )
            return result.stdout
        except Exception as e:
            print(f"Error fetching git tracking diff: {e}")
            sys.exit(1)


def scan_diff():
    diff_text = get_git_diff()
    if not diff_text:
        print("No structural changes detected in the assignments layout directory.")
        return

    ai_phrases = [
        r"insert your code here",
        r"generated by assistant",
        r"co-pilot choice",
        r"gpt-",
        r"openai",
        r"llm-generated",
        r"\# test case \d+",
        r"\# write your tests below",
    ]

    for phrase in ai_phrases:
        if re.search(phrase, diff_text, re.IGNORECASE):
            print(
                "\n❌ [GATE REJECTION] Automated AI boilerplate comment formatting signature detected."
            )
            print(
                "Instruction: Strip out boilerplate comments or templates. Document parameters manually."
            )
            sys.exit(1)

    lazy_test_pattern = r"def test_(case_?\d+|test_?\d+|\d+)\("
    if re.search(lazy_test_pattern, diff_text, re.IGNORECASE):
        print("\n❌ [GATE REJECTION] Generic non-semantic assertion index flagged.")
        print(
            "Instruction: Use readable descriptive names matching target scenarios (e.g., test_empty_input)."
        )
        sys.exit(1)

    if len(re.findall(r"assert ", diff_text)) > 30:
        print(
            "\n❌ [GATE REJECTION] Unusually dense asset cluster. Did an AI script loop generate this output?"
        )
        print(
            "Instruction: Consolidate structural layout using standard pytest.mark.parametrize."
        )
        sys.exit(1)

    print("✅ Advanced custom heuristic integrity verification passed.")


if __name__ == "__main__":
    scan_diff()
